server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/mertycom/CloudConfigRepoYml.git"
          default-label: main
          skip-ssl-validation: true
          username: mertycom
          password: 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